# ==============================================================================
# CONFIGURATION CLOUDFLARE PAGES / WORKERS
# ==============================================================================

name = "projet-jade"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Dossier de build pour Cloudflare Pages
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
RESEND_FROM_EMAIL = "onboarding@resend.dev"
